spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 200
      minimum-idle: 50

      connection-timeout: 20000
      max-lifetime: 270000
      keepalive-time: 240000

      register-mbeans: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  jmx:
    enabled: true

tosspayments:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  client-key: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
  confirm_url: ${TOSS_CONFIRM_URL}
  base_cancel_url: ${TOSS_CANCEL_URL}

fcm:
  service-account-file: key/fdbdproject.json
  topic-name: fdbdMessage
  project-id: fdbdproject

aws:
  s3:
    bucket: ${S3_BUCKET}
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}

server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    max-threads: 500
    max-connections: 10000
    accept-count: 4096

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      tomcat: true
  endpoint:
    metrics:
      enabled: true

  tracing:
    enabled: true
    sampling:
      probability: 0.01

  observations:
    annotations:
      enabled: true

  otlp:
    tracing:
      endpoint: http://172.31.22.88:4318/v1/traces


logging:
  level:
    org:
      hibernate:
        sql: error
        type.descriptor.sql.BasicBinder: error
        orm.jdbc.internal.LogicalConnectionImpl: error
      springframework.orm.jpa: error
      springframework.transaction: error
      springframework.web.client.RestTemplate: error
      com.mudosa.musinsa.common.client: error
